services:
  app:

    image: ghcr.io/igorkostoski/linkshortener:main
    container_name: linkshortener_app_server
    restart: unless-stopped
    ports:
      - "8080:8080"

    environment:
      - APP_PORT=8080
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=linkshortener_db
    depends_on:
      - db
    networks:
      - linkshortener_net
      - monitoring_net

  db:
    image: arm64v8/postgres:15
    container_name: linkshortener_db_server
    restart: unless-stopped
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: linkshortener_db


    volumes:
      - postgres_server_data:/var/lib/postgresql/data

    networks:
      - linkshortener_net

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus_server
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_server_data:/prometheus

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana_server
    restart: unless-stopped
    ports:
      - "3000:3000"   # <-- Fixed
    volumes:
      - grafana_server_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring_net



volumes:
  postgres_server_data:
  prometheus_server_data:
  grafana_server_data:

networks:
  linkshortener_net:
    driver: bridge
  monitoring_net:
    driver: bridge