build-and-push-docker-image:
  name: Build and Push Docker Image
  runs-on: ubuntu-latest
  needs: test-and-lint
  if: github.event_name == 'push'

  permissions:
    contents: read
    packages: write

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Add this step to set up Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }} # ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=sha,prefix=
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      id: build-and-push # Give this step an ID
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        # Ensure cache settings are still here
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # (Optional but good practice) Print image digest
    - name: Print image digest
      if: success() # Only run if the build-and-push step was successful
      run: echo "Pushed image digest: ${{ steps.build-and-push.outputs.digest }}"